[project]
name = "sshelf"
version = "0.1.0"
description = "A lightweight TUI to manage your SSH config easily"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "textual>=8.2.4",
]

[project.scripts]
sshelf = "sshelf.app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
